# Matrix algebra

In [1]:
import numpy as np
import random

In [4]:
A=np.random.randint(0,4,[3,1])
B=np.random.randint(0,4,[1,3])
A,B

(array([[1],
        [1],
        [2]]),
 array([[3, 1, 1]]))

In [7]:
C=np.dot(A,B)
C

array([[3, 1, 1],
       [3, 1, 1],
       [6, 2, 2]])

In [8]:
#Transpose
C.T

array([[3, 3, 6],
       [1, 1, 2],
       [1, 1, 2]])

In [9]:
# Solve Ax=B
A=np.random.randint(0,4,[3,3])
B=np.random.randint(0,4,[3,1])

In [10]:
#Linear Algebra
import numpy.linalg as LA
LA.solve(A,B)

array([[ 0.],
       [ 7.],
       [-4.]])

In [12]:
A_inv=LA.inv(A)
A_inv

array([[ 0. ,  0. ,  0.5],
       [ 3. , -1. , -3. ],
       [-2. ,  1. ,  1.5]])

In [13]:
np.dot(A_inv,A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
#Determinant
LA.det(A)

2.0

In [15]:
#Eigenvalues and Eigenvectors
LA.eigvals(A)

array([4.87905763+0.j        , 0.06047118+0.63738408j,
       0.06047118-0.63738408j])

In [17]:
LA.eig(A)

(array([4.87905763+0.j        , 0.06047118+0.63738408j,
        0.06047118-0.63738408j]),
 array([[ 0.54829226+0.j        ,  0.110038  +0.12747789j,
          0.110038  -0.12747789j],
        [ 0.80551942+0.j        , -0.83361315+0.j        ,
         -0.83361315-0.j        ],
        [ 0.22475335+0.j        ,  0.42890092-0.30458848j,
          0.42890092+0.30458848j]]))